stages:
  - build
  - test
  - security

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - cd portfolio
    - docker build -t portfolio-omar:$CI_COMMIT_SHORT_SHA .
    - docker save portfolio-omar:$CI_COMMIT_SHORT_SHA -o ../portfolio-image.tar
  artifacts:
    paths:
      - portfolio-image.tar
    expire_in: 1 hour
  only:
    - main

test:
  stage: test
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker load -i portfolio-image.tar
    - docker run -d --name test-container -p 8080:80 portfolio-omar:$CI_COMMIT_SHORT_SHA
    - sleep 3
    - docker exec test-container sh -c "wget -q -O- http://localhost:80 | head -5"
    - echo "Le conteneur demarre et repond correctement"
  only:
    - main

trivy-scan:
  stage: security
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - apk add --no-cache curl
    - curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
  script:
    - docker load -i portfolio-image.tar
    - trivy image --severity HIGH,CRITICAL --exit-code 0 --format table portfolio-omar:$CI_COMMIT_SHORT_SHA
  allow_failure: true
  only:
    - main

gitleaks-scan:
  stage: security
  image: alpine:latest
  before_script:
    - apk add --no-cache curl git
    - curl -sSL https://github.com/gitleaks/gitleaks/releases/download/v8.21.2/gitleaks_8.21.2_linux_x64.tar.gz -o gitleaks.tar.gz
    - tar -xzf gitleaks.tar.gz
    - mv gitleaks /usr/local/bin/
  script:
    - gitleaks detect --source . --verbose --exit-code 0
  allow_failure: true
  only:
    - main
